### ISSUE TITLE
no detection when GUI=false in 3D mode

### ISSUE THREAD

**Issue by icboredman** [introlab/find-object#100]
I use an rgbd camera with subscribe_depth=true and everything works beautifully in GUI mode. However, as soon as I change the gui parameter to false, no detection, no publishing of topics, nothing... I think I narrowed the problem down to line 182 in **find_object_2d_node.cpp**
If I change this line from:
`QObject::connect(camera, SIGNAL(imageReceived(const cv::Mat &)), findObjectROS, SLOT(detect(const cv::Mat &)));`
to:
`QObject::connect(camera, SIGNAL(imageReceived(const cv::Mat&, const QString&, double, const cv::Mat&, float)), findObjectROS, SLOT(detect(const cv::Mat&, const QString&, double, const cv::Mat&, float)));`
everything starts to work also without gui.
I don't fully understand the code structure, so wanted to ask if you think this is the right approach. Do you think it will have an impact on 2D mode (I haven't tried it)?
Thanks for your great work! I really enjoy rtabmap too! :)

**Comment by matlabbe** [comment]
It is fixed in the commit above. 2D mode still work with that change. Thx for the detailed report!
