### ISSUE TITLE
don't object detection

### ISSUE THREAD

**Issue by Fatemeh90** [introlab/find-object#103]
Hi, thank you for this application
For me, the kaze and Akaze algorithms don't work, and other algorithms identify key points but don't detection the object.

**Comment by matlabbe** [comment]
> the kaze and Akaze algorithms don't work
What do you mean? Are the options disabled? or just nothing is extracted from images? Which Find-Object version are you using? Also which OpenCV version are you using?

**Comment by Fatemeh90** [comment]
hello dear
nothing is extracted from images
find object 6.
open cv 3.4.7

‫‪matlabbe‬‏ <‪notifications@github.com‬‏> در تاریخ شنبه ۱۸ آوریل ۲۰۲۰ ساعت
۲:۲۱ نوشت:‬

**Comment by matlabbe** [comment]
Just gave a try with latest 3.4 opencv version, I cannot reproduce your problem.
![Screenshot from 2020-04-18 16-26-55](https://user-images.githubusercontent.com/2319645/79670512-a2cff480-8191-11ea-89cb-c817925baf10.png)

![Screenshot from 2020-04-18 16-27-32](https://user-images.githubusercontent.com/2319645/79670515-a95e6c00-8191-11ea-9811-4394b4ad3119.png)

**Comment by Fatemeh90** [comment]
‫‪matlabbe‬‏ <‪notifications@github.com‬‏> در تاریخ یکشنبه ۱۹ آوریل ۲۰۲۰
ساعت ۰:۵۹ نوشت:‬
