### ISSUE TITLE
How to change default detector and descriptor in "find-object-2d"

### ISSUE THREAD

**Issue by WhereHvaeAllTheFlowerGone** [introlab/find-object#109]
I want to change the default SIFT detector and descriptor to ORB, however I don't find where can I make this changes. I searched the the code in find-object-2d package but don't know how to do

**Comment by matlabbe** [comment]
Depending on the OpenCV version used, the default can be different. See here to change default (change the index in the string):
https://github.com/introlab/find-object/blob/856d7f0d62c4fe5a7606a2ce6a0f5c9dd6fd80fa/include/find_object/Settings.h#L115-L126

**Comment by WhereHvaeAllTheFlowerGone** [comment]
> Depending on the OpenCV version used, the default can be different. See here to change default (change the index in the string):
> https://github.com/introlab/find-object/blob/856d7f0d62c4fe5a7606a2ce6a0f5c9dd6fd80fa/include/find_object/Settings.h#L115-L126

Thank you for your answering! I'll check my OpenCV version and change the corresponding settings.
