### ISSUE TITLE
the position of the detected object is not correct!!

### ISSUE THREAD

**Issue by Delbina** [introlab/find-object#123]
hi,

I have a robot that the D435i camera is attached to the bulk-head. i have extracted the position of the object relative to the camera, but it is not correct!
after launching find_3d_object.launch, i can see that the position of the detected object is not correct: in the following you can see one example. i have considered camera_color_optical_frame as the fixed frame. so i expect that the objects on the right hand side of my camera have a positive x and negative y, and positive for both x and y for those objects on the left side. but you can see that for the objects in the left side, both x and y are negative? why?
i have considered:
 X forward
 Y left
 Z up

one more thing is that we expect by the movement of the vehicle toward objects, distance between them decrease, but the output sometime is increase and sometimes decrease.!!!!

![Screenshot from 2022-05-25 11-06-21](https://user-images.githubusercontent.com/32564347/170239651-924c465d-bf05-4cf4-98e9-5d92be282cad.png)

object_44 in the left sie, this is the plot about x position over time, from the time that it has been detected, and up to the time that the object disappear from the point of view of camera (vehicle is moving on the railway track)
![image](https://user-images.githubusercontent.com/32564347/170274052-087f48b6-a96f-4ad9-bde0-a4f755934714.png)

object on the right hand.
![image](https://user-images.githubusercontent.com/32564347/170274635-b05d1694-2eca-4837-9aaa-ed38f16eb073.png)

what is the procedure when we have a camera is on a moving vehicle?!
Thanks

**Comment by Delbina** [comment]
I have plotted one more graph, which shows X, Y, and Z.
i have omitted the negative sign (i mean now I have the absolute values).

![sege](https://user-images.githubusercontent.com/32564347/170687087-91026a6a-32b8-4f89-84a7-76a4d6d4978c.png)

**Comment by matlabbe** [comment]
See my answer here: https://answers.ros.org/question/401381/the-position-of-the-detected-object-is-not-correct/?answer=405981#post-id-405981
