### ISSUE TITLE
Support of find-object for ROS2 is available?

### ISSUE THREAD

**Issue by goyalvarun02** [introlab/find-object#131]
Hi ,

May I know if github of find-object for ROS 2 is available Please share the path .

or if not available May I know when can expect the ros2 of find-object.

Thanks

**Comment by Bread2018** [comment]
i have the same question, did you find the solution?

**Comment by matlabbe** [comment]
find_object has been ported to ROS2. The main branch is compatible ROS1 and ROS2, follow installation instructions under ROS2 section of the readme.
