### ISSUE TITLE
Where to find example file ?

### ISSUE THREAD

**Issue by TapleFlib** [introlab/find-object#138]
@matlabbe hello, I'm working on a pick and place project and I need to add the object tf and send it to my robotic arm, but the link that you provide on another comment : [https://github.com/introlab/find-object/blob/master/src/ros/tf_example_node.cpp](url) is unavailable , do you know where can I see the example code? I'm new to ROS and struggling with the coding subscriber and publisher stuff, Thankyou !

**Comment by matlabbe** [comment]
New link: https://github.com/introlab/find-object/blob/master/src/ros1/tf_example_node.cpp
