### ISSUE TITLE
Empty frame ID

### ISSUE THREAD

**Issue by takahiko-hasegawa-hdjp** [introlab/find-object#145]
HI there Im using ROS2 interface of find object and i encountered an issue. 
 when object is detected, it publishes a topic called /objectsStamped but the the frameId is always empty.

in FindObjectROS.cpp therte is a line of code that extracts frame ID from header but seems empty.

> 			// use same header as the input image (for synchronization and frame reference)
> 			msgStamped.header.frame_id = header.frameId_.toStdString();

and I suppose the function of this FindObjectROS::publish is a callback function of the following	

> 			QObject::connect(
> 					&mainWindow,
> 					SIGNAL(objectsFound(const find_object::DetectionInfo &, const find_object::Header &, const cv::Mat &, float)),
> 					findObjectROS_,
> 					SLOT(publish(const find_object::DetectionInfo &, const find_object::Header &, const cv::Mat &, float)));
> 

How can I resolve this issue?

**Comment by matlabbe** [comment]
Does the image topic sent to `find_object` have a `frame_id` set?

**Comment by takahiko-hasegawa-hdjp** [comment]
OK I got it now! frame ID wasnt set on my rgb topic. 

Another question not related but is there a way to save multiple objects to a folder but shares the same ID?
so there is one object that i want to detect but depending on the lighting condition and some angle difference the detection is not great. So I want to save multiple "images" for same object. Can I do that?

**Comment by matlabbe** [comment]
You can create a settings file and pass it to `find_object_2d` node: http://wiki.ros.org/find_object_2d

Each image has its own unique ID, you would need to combine yourself the range of IDs that represent the same object. For example, IDs 1 to 9 are object A, IDs 10 to 19 are object B....

**Comment by takahiko-hasegawa-hdjp** [comment]
Thank you!! Thats sorted now!

The problem I have is that I have multiple landmarks in my environment where the shape of those landmarks are identical but the colours are differnt. 

I understand that the feature matching relies on the descriptor of the keypoints extracted whichi do not consider colour. Is there a way to utilise colour information?

Thanks!
