### ISSUE TITLE
no objects loaded from path

### ISSUE THREAD

**Issue by AlexxxBeck** [introlab/find-object#16]
Hello,

at first when I used the find object program everything worked fine. I think that I accidentally closed the add object session and afterwards when I tried to restart the program I get the following error:

alex@alex-UX303LAB:~$ rosrun find_object_2d find_object_2d image:=image_raw
[ INFO] [1457440617.750504616]: gui=0
[ INFO] [1457440617.750581664]: objects_path=~/objects
[ INFO] [1457440617.750599829]: session_path=
[ INFO] [1457440617.750615618]: settings_path=~/.ros/find_object_2d.ini
[ INFO] [1457440617.750630166]: subscribe_depth = false
[ INFO] [1457440617.750645655]: obj_frame_prefix = object
[ERROR] [1457440617.754217255]: No objects loaded from path "/home/alex/objects"

I can still start the program with the Kinect v2 but I still can't manage to add pictures.

![can t add picture](https://cloud.githubusercontent.com/assets/17646377/13601884/67b63340-e533-11e5-8f09-269225136134.png)

I already tried reinstalling but it didn't work unfortunately

**Comment by matlabbe** [comment]
Normally the next steps should work:

1) Add objects
```bash
$ rosrun find_object_2d find_object_2d image:=/camera/rgb/image_rect_color
[ INFO] [1457545635.506655098]: gui=1
[ INFO] [1457545635.507246567]: objects_path=
[ INFO] [1457545635.507463640]: session_path=
[ INFO] [1457545635.507633651]: settings_path=/home/mathieu/.ros/find_object_2d.ini
[ INFO] [1457545635.507846883]: subscribe_depth = false
[ INFO] [1457545635.508014447]: obj_frame_prefix = object
```
 * Do "Edit->Add object from scene...".
 * When you quit find-object (don't do ctrl-c, close the window), you will be asked to save the objects. Press "yes" and select a directory (i.e., "~/objects").

2) Open again **find_object_2d** but this time with the objects path set:
```bash
$ rosrun find_object_2d find_object_2d image:=/camera/rgb/image_rect_color _objects_path:=~/objects
[ INFO] [1457545635.506655098]: gui=1
[ INFO] [1457545635.507246567]: objects_path=~/objects
[ INFO] [1457545635.507463640]: session_path=
[ INFO] [1457545635.507633651]: settings_path=/home/mathieu/.ros/find_object_2d.ini
[ INFO] [1457545635.507846883]: subscribe_depth = false
[ INFO] [1457545635.508014447]: obj_frame_prefix = object
```
 * The window should open with already an object loaded (Open "View->Objects" panel ).

cheers
