### ISSUE TITLE
3D position of the objects erro  exit code -11

### ISSUE THREAD

**Issue by huangjian4** [introlab/find-object#17]
Hi,I am using ROS Indigo and Kinect(for XBOX360).

I am trying this [tutorial](http://wiki.ros.org/find_object_2d#),and I got some problems about 3D position of the objects.

`roslaunch openni_launch openni.launch depth_registration:=true`
`roslaunch find_object_2d find_object_3d.launch`
`rosrun rviz rviz`
every thing seems works well,but when I tried to add an object,then present an object, then Select the features extracted from the object, return to main screen,

erro happened like：

[ WARN] [1459320214.341369045]: "object_10" passed to lookupTransform argument source_frame does not exist. 
[ WARN] [1459320214.841072544]: Object 10 detected, center 2D at (459.562181,229.519383), but invalid depth, cannot set frame "object_10"! (maybe object is too near of the camera or bad depth image)

[ WARN] [1459320214.841452733]: "object_10" passed to lookupTransform argument source_frame does not exist. 
[ WARN] [1459320215.336902142]: TF to MSG: Quaternion Not Properly Normalized
[ WARN] [1459320215.337123950]: TF to MSG: Quaternion Not Properly Normalized
[find_object_3d-1] process has died [pid 1978, exit code -11, cmd /opt/ros/indigo/lib/find_object_2d/find_object_2d rgb/image_rect_color:=camera/rgb/image_rect_color depth_registered/image_raw:=camera/depth_registered/image_raw depth_registered/camera_info:=camera/depth_registered/camera_info __name:=find_object_3d __log:=/home/exbot/.ros/log/8bddd226-f642-11e5-9962-78929c842512/find_object_3d-1.log].
log file: /home/exbot/.ros/log/8bddd226-f642-11e5-9962-78929c842512/find_object_3d-1*.log

How can I deal with it? thx!

**Comment by matlabbe** [comment]
Hi,

Do you use the binaries or from source? I cannot reproduce the error. If you are using the source, you could activate the debug log at the beginning of the [main()](https://github.com/introlab/find-object/blob/84cf6280ac9aadca3145b524453b710bd34cea5e/src/ros/find_object_2d_node.cpp#L68):
```cpp
#include "find_object/utilite/ULogger.h"

int main(int argc, char** argv)
{
   ULogger::setType(ULogger::kTypeConsole);
   ULogger::setLevel(ULogger::kDebug);
   ...
```
We will have more information on the console before it crashes.

cheers

**Comment by huangjian4** [comment]
Hi,
It works well in another computer,maybe there are some problems for my computer,thanks for your reply!

sincerely.
