### ISSUE TITLE
Cannot open SURF/SIFT in Find_object_2d

### ISSUE THREAD

**Issue by gabrielarpino** [introlab/find-object#22]
Hey, I am trying to use find_object_2d with RTABMAP and it works fine, except that I cannot use the SURF or SIFT algorithms under the feature2D tab in the Find-Object UI. I built OpenCV from source, and cloned the opencv_contrib module folder. Why are SURF and SIFT not showing up and how could i get them to show up? Thanks.

also, when i run sudo apt-cache search opencv, one of the lines printed are:

libopencv-nonfree2.4 - computer vision contrib library
libopencv-nonfree-dev - development files for libopencv-nonfree

Which means I also have the nonfree module. Why is find_object_2d not syncing with any of these so that I can use SURF/SIFT? Thanks.

ALSO: my nearest neighbour strategies options are only BruteForce and Lsh (the other ones are not available, such as Kmeans). How would I go about adding these?

Best,

Gabriel

**Comment by matlabbe** [comment]
Hi Gabriel,

You should build find_object_2d from [source](https://github.com/introlab/find-object#find_object_2d-ros-package) so that it can link on your opencv libraries built from source too.

cheers

**Comment by gabrielarpino** [comment]
Thank you very much :)

**Comment by gabrielarpino** [comment]
Hi Matlabbe,

Sorry to bother you again, I installed find_object_2d from source, but I am not able to perform rosrun find_object_2d find_object_2d image:=image_raw, it says "package 'find_object_2d' not found. Would you know how I might be able to fix it? Thanks :)

**Comment by matlabbe** [comment]
Hi,

Make sure you uninstalled the find_object_2d binaries and you sourced your `~/catkin_ws/devel/setup.bash`.
```bash
$ source ~/catkin_ws/devel/setup.bash
$ rosrun find_object_2d find_object_2d image:=image_raw
```
cheers

**Comment by gabrielarpino** [comment]
How do I link find_object_2d with my OpenCV libary built from source?

**Comment by matlabbe** [comment]
If you installed OpenCV in `/usr/local` (default), cmake should detect it first when building `find_object_2d`. You may have to do a clean build to make sure that it links to correct library:
```bash
$ cd ~/catkin_ws/build
$ rm -r *
$ cd ..
$ catkin_make
```

If OpenCV is not installed in `/usr/local`, you can set `OpenCV_DIR` to directory containing the generated `OpenCVConfig.cmake` (here pointing to OpenCV's build directory):
```bash
$ catkin_make -DOpenCV_DIR=~/opencv_src/build
```

**Comment by animez4me** [comment]
Hi, 
Sorry to bring this back up again. But SIFT/SURF are greyed out for me, even when I built from source. I noticed that my opencv is located in /usr/include however I do not see the OpenCVConfig.cmake file?

Thanks,

**Comment by matlabbe** [comment]
The opencv located in /usr/include would be the standard Opencv binaries which don't have SIFT/SURF. You have to build OpenCV from source with nonfree module (OpenCV2) or opencv_contrib (OpenCV3). If you have built opencv from source and installed in /usr/local and rtabmap is still using opencv from /usr, remove CMakeCache.txt from rtabmap's build directory and re-rerun cmake.

cheers

**Comment by animez4me** [comment]
Thanks a lot, got it now!
