### ISSUE TITLE
3d position error

### ISSUE THREAD

**Issue by shixinlishixinli** [introlab/find-object#26]
hi ,i am using ros indigo and realsense sr300 .sometimes i can get 3d position of object but sometimes i have problems about 3d position 
[ INFO] [1475113598.537434025]: Object_64 [x,y,z] [x,y,z,w] in "/map" frame: [0.139000,0.033985,0.016190] [-0.981934,1.133853,-0.013125,1.188766]
[ INFO] [1475113598.537483947]: Object_64 [x,y,z] [x,y,z,w] in "camera_rgb_optical_frame" frame: [-0.033985,-0.016190,0.139000] [0.000000,0.000000,-0.013125,1.188766]
[ WARN] [1475113598.740891659]: Object 64 detected, center 2D at (202.716570,183.286647), but invalid depth, cannot set frame "object_64"! (maybe object is too near of the camera or bad depth image)
and i run rviz to find that the depth information is good

**Comment by matlabbe** [comment]
The approach used to find object's 3D pose is quite simple. See code [here](https://github.com/introlab/find-object/blob/48e6ea0147da79b0bdc59886c1c9ffe89998dc9c/src/ros/FindObjectROS.cpp#L89-L91). It assumes that the object is planar (like a book cover).
![untitled](https://cloud.githubusercontent.com/assets/2319645/18966740/60b13446-8650-11e6-8c9f-f2f2411e65eb.png)
If any of these 3 points have null depth value, the TF is not published. We could change the [getDepth](https://github.com/introlab/find-object/blob/48e6ea0147da79b0bdc59886c1c9ffe89998dc9c/src/ros/FindObjectROS.cpp#L183) method to look for a valid depth around (small window of 1-2 pixels) these points if they are null.

**Comment by shixinlishixinli** [comment]
is there any reason about my camera is realsense sr300? could i need to change some constant ?

**Comment by matlabbe** [comment]
Can you show the depth image of the camera, with your object in sight?

**Comment by shixinlishixinli** [comment]
![111](https://cloud.githubusercontent.com/assets/20768380/19209655/98018516-8d41-11e6-8237-452faa88011f.png)

**Comment by shixinlishixinli** [comment]
![1162458945](https://cloud.githubusercontent.com/assets/20768380/19209686/4a458f2e-8d42-11e6-9c3c-e7783dc3d7cb.jpg)
i use rviz to view the depth image ,and the depth image is very good .the distance between the object and camera can be 15cm

**Comment by matlabbe** [comment]
Can you record a little rosbag with the topics that you feed to `find_object`? and posting the image of the object used by `find_object`.

**Comment by shixinlishixinli** [comment]
i think i have already debug the error. because the depth image can not correspond to rgb image ,so some times i can not receive the right depth data.

**Comment by shixinlishixinli** [comment]
really thank you for your help

**Comment by matlabbe** [comment]
Yes, make sure the depth is registered to color camera.

cheers

**Comment by onlooker82** [comment]
> i think i have already debug the error. because the depth image can not correspond to rgb image ,so some times i can not receive the right depth data.

Dear Shixinli

I met the same problem when using realsense L515, it's RGBD camera color width and height is 1280X720 but depth width and height is 640X480.
Could u share how to corrspond the rgb image and depth image?

Thanks very much.

**Comment by matlabbe** [comment]
See https://github.com/IntelRealSense/realsense-ros/issues/1405#issuecomment-719114875 if by enabling `align_depth` it could help.

**Comment by onlooker82** [comment]
> See [IntelRealSense/realsense-ros#1405 (comment)](https://github.com/IntelRealSense/realsense-ros/issues/1405#issuecomment-719114875) if by enabling `align_depth` it could help.

It works! ,thx very much!
