### ISSUE TITLE
error occurs while end of the adding object from taking a picture

### ISSUE THREAD

**Issue by ljxin1993** [introlab/find-object#27]
Hi，I'm using roslaunch find_object_2d find_object_3d_kinect2.launch to find object.But error occurs at the end of the adding object from taking a picture .Here are some error information ：

[ INFO] [1478596610.537800121]: gui=1
[ INFO] [1478596610.537872437]: objects_path=
[ INFO] [1478596610.537898265]: session_path=
[ INFO] [1478596610.537921191]: settings_path=~/.ros/find_object_2d.ini
[ INFO] [1478596610.537942808]: subscribe_depth = true
[ INFO] [1478596610.542034484]: object_prefix = object
[ INFO] [1478596610.543486549]: find_object_ros: queue_size = 10
OpenCV Error: Unsupported format or combination of formats (type=0
) in buildIndex_, file /home/ncrc6/opencv-2.4.13/modules/flann/src/miniflann.cpp, line 315
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'cv::Exception'
  what():  /home/ncrc6/opencv-2.4.13/modules/flann/src/miniflann.cpp:315: error: (-210) type=0
 in function buildIndex_

[find_object_3d-1] process has died [pid 6662, exit code -6, cmd /home/ncrc6/AutoObjSearch_ws/devel/lib/find_object_2d/find_object_2d rgb/image_rect_color:=/kinect2/qhd/image_color_rect depth_registered/image_raw:=/kinect2/qhd/image_depth_rect depth_registered/camera_info:=/kinect2/qhd/camera_info __name:=find_object_3d __log:=/home/ncrc6/.ros/log/0bc64bf2-a594-11e6-8b6f-b808cf28480e/find_object_3d-1.log].
log file: /home/ncrc6/.ros/log/0bc64bf2-a594-11e6-8b6f-b808cf28480e/find_object_3d-1*.log

Could you give me some advice ? Thank you!

**Comment by matlabbe** [comment]
I cannot reproduce the error:
```bash
$ roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true
$ roslaunch find_object_2d find_object_3d_kinect2.launch
```

then "Edit->Add object from scene...", take picture, select object and add it.

Is it crashing every time you add a new object?

**Comment by ljxin1993** [comment]
I have solved this problem by installing opencv nonfree.
