### ISSUE TITLE
Unable to detect object using Kinect v2 in Ros indigo

### ISSUE THREAD

**Issue by vacky11** [introlab/find-object#28]
I was successfully able to add the object add the object from the scene using the gui of Find-Object. But it is not able to detect the object

I am using following two commands as given in documentation 

roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true
roslaunch find_object_2d find_object_3d_kinect2.launch

please help

**Comment by matlabbe** [comment]
Show examples of objects you want to detect. I recommend to start with book covers (with a lot of visual features) to see how it works and its limitations. Featureless objects are difficult to detect with find-object.

**Comment by vacky11** [comment]
Thanks for replying.
I tried some different object and now it is working. 

Thank you

**Comment by vacky11** [comment]
Is there any way to detect an object just by its color using find-object ?

**Comment by matlabbe** [comment]
No, you may find more info searching "opencv color detection".

**Comment by vacky11** [comment]
okay thanks
