### ISSUE TITLE
find_object crashes after adding object to scene or adding object by files

### ISSUE THREAD

**Issue by MaskedAfrican** [introlab/find-object#29]
Hi, I'm having trouble running find-object as it keeps crashing and I keep getting the following error:

```
OpenCV Error: Unsupported format or combination of formats (type=0
) in buildIndex_, file /home/user/opencv-2.4.13/modules/flann/src/miniflann.cpp, line 315
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/user/opencv-2.4.13/modules/flann/src/miniflann.cpp:315: error: (-210) type=0
 in function buildIndex_

[find_object_3d-1] process has died [pid 4635, exit code -6, 
cmd /home/user/catkin_ws/devel/lib/find_object_2d/find_object_2d rgb/image_rect_color:=/kinect2/qhd/image_color_rect depth_registered/image_raw:=/kinect2/qhd/image_depth_rect 
depth_registered/camera_info:=/kinect2/qhd/camera_info __name:=find_object_3d __log:=/home/user/.ros/log/e0a800d0-f234-11e6-91b5-e82aeaab80ce/find_object_3d-1.log].
log file: /home/user/.ros/log/e0a800d0-f234-11e6-91b5-e82aeaab80ce/find_object_3d-1*.log

```

This happens whenever I import my object or use the take picture option to add an object. I tried the suggestions at the following [link](https://github.com/introlab/find-object/issues/27) and this is what my setup currently looks like:
![image](https://cloud.githubusercontent.com/assets/8877826/22905162/220d46be-f237-11e6-90c9-4546cd7f32b8.png)

Could you please kindly help?

**Comment by matlabbe** [comment]
Did you try the latest code from source? It looks like there is a commit about OpenCV 2.4.13 that may be related to this error: https://github.com/introlab/find-object/commit/77b95d6b8c7cbbadc985cfe4d4142066afb0599e

**Comment by MaskedAfrican** [comment]
I reverted to 2.4.8 and everything is all good now

**Comment by agribot2** [comment]
Find-object crashes about 1 in 3 times on windows 7 laptop.

 version is 0.6, opencv 3.0.0 with non-free.
Installed on a 64 bit Windows 7, on a Sony VPCF1 type laptop, running Intel i7 processor

Find-Object was installed by downloading and running the win-64 exe installer file.
 The find-object.exe file is date  10/07/2015, size 118KB

example of operation;-
start up Find-Object by clicking on the above .exe file
press space bar for default camera (laptop)
pause camera
add object from file
start camera
crash
