### ISSUE TITLE
Save photo/video on detection

### ISSUE THREAD

**Issue by olegi4sam** [introlab/find-object#31]
Thanks for one of the easiest solutions for usual users.

Tell me please how can I save photo/video on object detection from webcam?

Thank You!

**Comment by matlabbe** [comment]
Do you mean a screenshot or a screen recording?

**Comment by olegi4sam** [comment]
I mean saving picture (or video) from camera when object detected.

Like autoPauseOnDetection, only AutoSaveImageOnDetection (or X seconds of video from detection moment)

![figure](https://cloud.githubusercontent.com/assets/25985309/23954520/2a80a824-09a0-11e7-8393-ae1fb846c9da.png)
![screenshot 2017-03-15 at 16 53 53](https://cloud.githubusercontent.com/assets/25985309/23954522/2ab3ac10-09a0-11e7-83bf-14b215bd4f55.png)

**Comment by matlabbe** [comment]
Hi,

thx for the precision. I added autoScreenshotPath in this commit https://github.com/introlab/find-object/commit/dc042fe418399c9bfe8ce621e23b3b95e92337dd, it saves the current image view into that directory on detection.

cheers,
Mathieu
