### ISSUE TITLE
Is it possible to stream video from and android ip camera over http?

### ISSUE THREAD

**Issue by energabos** [introlab/find-object#32]
i can't get it to work with camera over tcp/ip. Please shed some light on this!

**Comment by matlabbe** [comment]
The [TCP example](https://github.com/introlab/find-object/wiki/TcpRequest) is more about a single image request than an image stream over TCP/IP. 

However, reading this [post](http://answers.opencv.org/question/133/how-do-i-access-an-ip-camera/):

> You need to compile OpenCV with ffmpeg support.

it could then be possible by setting the address of the camera in `Camera/mediaPath` parameter. 

cheers,
Mathieu

**Comment by energabos** [comment]
Thanks matlabbe, it works!
