### ISSUE TITLE
Problem of "terminate called after throwing an instance" and failure to use "file -> load/save"

### ISSUE THREAD

**Issue by jiangfalcon** [introlab/find-object#34]
Hello, 
This is a great ROS package.
However, I got some problems when I use it.
There are two problems below:
(1)
The first one is:
Sometimes, the program crashed after running for a while.
Terminal would also show something like the photo below.
How could I solve this problem?

![screenshot 2017-03-27 17 27 27](https://cloud.githubusercontent.com/assets/20721767/24352946/21982340-131e-11e7-9f06-7622070be062.png)

(2)
The second one is:
When I tried to click the options "file -> load/save", the program would get stuck for a while and always show nothing like the photo below.
![screenshot 2017-03-27 17 22 20](https://cloud.githubusercontent.com/assets/20721767/24352958/2f070abe-131e-11e7-99e3-a2f188d21b66.png)

Please help me solve these problems.
Thanks a lot~

**Comment by matlabbe** [comment]
Hi,

I [updated](https://github.com/introlab/find-object/commit/6337d4efb678aac3c041fb187250764ebff8ac58) the code with new option General/debug to show more debug info on terminal. This may help to see more exactly where the assert happens. For the problem, it would be Qt related [when opening a FileDialog](https://github.com/introlab/find-object/blob/9525a556179551d2727cf091f318ef9bb4dbf0ad/src/ObjWidget.cpp#L617). What is your system?

cheers,
Mathieu

**Comment by jiangfalcon** [comment]
Hi,

Thanks for your response!
I tried to run the updated program.
It seems that the program always terminated after the number of descriptors extracted was over the max. number I set.
In my test, I set the max. number of SIFT descriptors is 800.
You can see the two screenshots below. 
When 801 descriptors extracted, it might not terminated.
However, when the program terminated, the previous INFO always showed 801 descriptors extracted.

![screenshot 2017-03-28 18 47 02](https://cloud.githubusercontent.com/assets/20721767/24401530/625c8fd2-13e7-11e7-9ed4-fca62e328cf0.png)


![screenshot 2017-03-28 18 47 20](https://cloud.githubusercontent.com/assets/20721767/24401537/667ab12a-13e7-11e7-8d46-7b90bd96c813.png)

Besides, the last screenshot shows the version of Qt, Ubuntu, and OpenCV in my system.

![screenshot 2017-03-28 18 51 31](https://cloud.githubusercontent.com/assets/20721767/24401597/9afe45c4-13e7-11e7-849f-9bbbd7d0673c.png)

Thanks~

**Comment by matlabbe** [comment]
Hi,

The crash should be fixed by https://github.com/introlab/find-object/commit/419a8a6f5138670e84db89cea87ba9f39784a470

For the dialog, I reproduced the same problem on Ubuntu 14.04. We should **pause** the camera before opening clicking on actions opening a File Dialog. On Windows, there is no such problem.

cheers,
Mathieu

**Comment by jiangfalcon** [comment]
Thank you so much ^_^
