### ISSUE TITLE
no object detected [homography computed disabled]

### ISSUE THREAD

**Issue by arunmandal53** [introlab/find-object#37]
I want to speed up the object detection by disabling homography computed. But it says object not detected. Please to detect object (compromising accuracy) without homography computed enabled.

**Comment by matlabbe** [comment]
Hi,

homography is required to filter keypoints that are outliers (with RANSAC) when detecting objects, so it cannot be disabled if we want to detect objects. However, in this [commit](https://github.com/introlab/find-object/commit/ca1e1dccdec8386b5878e1dbcbe975e681e8e5c4), I updated the code to use new parameters **maxIter** and **confidence** of [cv::findHomography()](http://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#findhomography). You can lower the maxIterations (default 2000) to save some time. This is only available when built against OpenCV3:
![screenshot from 2017-04-27 14-37-00](https://cloud.githubusercontent.com/assets/2319645/25499156/91b96d6c-2b58-11e7-8510-ecd18bc53b88.png)

cheers,
Mathieu
