### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by jonyballerino** [introlab/find-object#38]
Hi.

I'm trying to build find-object package for ROS (release v0.6.0 because of OpenCV 3), but compilation failed with this error:
```
In file included from /home/user/catkin_ws/src/find_object_2d/src/MainWindow.cpp:28:0:
/home/user/catkin_ws/src/find_object_2d/src/../include/find_object/MainWindow.h:35:29: fatal error: QtGui/QMainWindow: No such file or directory
 #include <QtGui/QMainWindow>
```
I use Ubuntu 14.4 and ROS indigo.
What is? How i can resolve it?
Thanks

**Comment by matlabbe** [comment]
Use latest code from master branch, this is fixed (should be `#include <QMainWindow>`). 
```bash
git clone https://github.com/introlab/find-object.git
```
