### ISSUE TITLE
Fps Rate

### ISSUE THREAD

**Issue by AlexTape** [introlab/find-object#4]
Hey,

is there any option/parameter to display framerates?

Kindly

**Comment by matlabbe** [comment]
See the third screenshot on the main page. The rate is shown on top of the scene. Example: "Camera (10 Hz - 5 Hz)" where the first rate is the parameter "Camera/imageRate" and the second is the actual framerate.

You can also see the Statistics panel (Menu View->Statistics) for more timing information.

cheers

**Comment by AlexTape** [comment]
Ah, thank you! :+1:
