### ISSUE TITLE
Is  possible using this package with gazebo kinect plugin

### ISSUE THREAD

**Issue by jacknlliu** [introlab/find-object#40]
If I use gazebo kinect plugin scan the virtual scene, is it possible using this package to detect objects in the virtual scene?

**Comment by matlabbe** [comment]
Yes, just remap the corresponding topics.

**Comment by jacknlliu** [comment]
@matlabbe  Thank you for your reply. I try it and it works!

I modify launch file `/opt/ros/kinetic/share/find_object_2d/launch/find_object_3d.launch`,
remap topics  
 `rgb/image_rect_color` to `/3dcamera/rgb/image_raw`,     
 `depth_registered/image_raw` to `/3dcamera/depth/image_raw`,     
 `depth_registered/camera_info` to `/3dcamera/depth/camera_info`.

The contents of the file partly like,
```
	<node name="find_object_3d" pkg="find_object_2d" type="find_object_2d" output="screen">
		<param name="gui" value="true" type="bool"/>
		<param name="settings_path" value="~/.ros/find_object_2d.ini" type="str"/>
		<param name="subscribe_depth" value="true" type="bool"/>
		<param name="objects_path" value="" type="str"/>
		<param name="object_prefix" value="object" type="str"/>
		
		<remap from="rgb/image_rect_color" to="/3dcamera/rgb/image_raw"/>
		<remap from="depth_registered/image_raw" to="/3dcamera/depth/image_raw"/>
		<remap from="depth_registered/camera_info" to="/3dcamera/depth/camera_info"/>
	</node>
```

Hope this will help some future readers.

**Comment by tiberium24** [comment]
I tried what you say but for detecting an object i do not get 3D information.

Object 13 detected, center 2D at (330.997294,201.964507), but invalid depth, cannot set frame "object_13"! (maybe object is too near of the camera or bad depth image)

**Comment by matlabbe** [comment]
As the warning is saying, there are no valid depth values at the centre of the object. Can you post a screenshot of the rgb and depth image when the object should be detected?
