### ISSUE TITLE
Error: Find-Object doesn't work when using realsense camera R200

### ISSUE THREAD

**Issue by zhongxin882001** [introlab/find-object#43]
Hello,
I'm planning to use this for my own project with realsense camera R200 now.
 I  followed the example on http://wiki.ros.org/find_object_2d#A3D_position_of_the_objects.

when I start the camera driver    roslaunch realsense_camera r200_nodelet_rgbd.launch
![screenshot from 2017-06-30 12 16 53](https://user-images.githubusercontent.com/27988710/27719592-7fd12ad2-5d8e-11e7-85e5-f0336c8f63c3.png)

and  roslaunch find_object_2d find_object_3d.launch

![screenshot from 2017-06-30 12 19 42](https://user-images.githubusercontent.com/27988710/27719607-9b7be5ba-5d8e-11e7-92a1-d43aa759aee5.png)
then I got 
![screenshot from 2017-06-30 12 22 53](https://user-images.githubusercontent.com/27988710/27719671-eb1a44b8-5d8e-11e7-96b7-c74d1fdd7b2b.png)
I checked these three topics they are pulished correctly
![screenshot from 2017-06-30 12 27 39](https://user-images.githubusercontent.com/27988710/27719757-87dd40de-5d8f-11e7-9882-d143ba827f53.png)
![screenshot from 2017-06-30 12 32 40](https://user-images.githubusercontent.com/27988710/27719875-502a360a-5d90-11e7-9372-04ffe67b800d.png)

Does anyone know what the problem is?
Thanks!

**Comment by matlabbe** [comment]
There is a typo in the camera_info toptic: "/sw_register/"
