### ISSUE TITLE
Error when compiling from source

### ISSUE THREAD

**Issue by octy40** [introlab/find-object#44]
When compiling from source with catkin_make, I was running into this issue:

Vocabulary.cpp:249:109: error: no matching function for call to ‘cv::flann::Index::build(cv::Mat&, cv::flann::LinearIndexParams, cvflann::flann_distance_t)’

Looking at that particular line in Vocabulary.cpp indicated that it was looking for a specific version of opencv. The one hardcoded in is 2.4.12 (https://github.com/introlab/find-object/blob/kinetic-devel/src/Vocabulary.cpp#L246) and I had 2.4.13. I fixed it by replacing the 12 with 13 and the issue went away.

Just highlighting this since no specific version of Opencv was required for this package.

**Comment by matlabbe** [comment]
This is already fixed in master branch: https://github.com/introlab/find-object/blob/master/src/Vocabulary.cpp#L246
