### ISSUE TITLE
IndexParams has private copy constructor

### ISSUE THREAD

**Issue by waleedq** [introlab/find-object#46]
Hello, 
I've faced this issue while compiling code from source, the error message is 

"base class 'cv::flann::IndexParams' has private copy constructor"

I guess the latest opencv have some [changes](https://github.com/opencv/opencv/pull/9580/files#diff-8012c5becc1fc2dd43c6fecb21bad948) that made the copy constructor for IndexParams to be private and disabled copying it, so this would lead to some code changes to make the function getFlannSearchParams to be a return by reference instead value.

**Comment by matlabbe** [comment]
Thx for reporting!
