### ISSUE TITLE
Failure to detect ros/catkin build

### ISSUE THREAD

**Issue by nxdefiant** [introlab/find-object#47]
When building with it e.g.

> catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/kinetic

a non-ros version is build. So detecting the catkin build with 

> CATKIN_TOPLEVEL OR CATKIN_BUILD_BINARY_PACKAGE OR CATKIN_SKIP_TESTING OR CATKIN_ENABLE_TESTING

is obviously not enough. As a workaround -DCATKIN_SKIP_TESTING=1 can be set on the commandline.

**Comment by matlabbe** [comment]
CATKIN_DEVEL_PREFIX seems set with this kind of build, so I added it to the catkin detection.

Thx for reporting,
Mathieu

**Comment by nxdefiant** [comment]
Confirmed, thank you.
