### ISSUE TITLE
Support for D400 Realsense cameras?

### ISSUE THREAD

**Issue by fiorano10** [introlab/find-object#51]
Is it possible to use RealSense D400 series RGBD cameras to for pose estimation ?

**Comment by fiorano10** [comment]
I am able to use the find_object_2d package, and remapped the topics. But it keeps publishing the 'no objects were identified' message, what could be the issue? I need to find the person object, and get the pose.

**Comment by matlabbe** [comment]
Is the object detected in the Find-Object ui?

**Comment by fiorano10** [comment]
It wasn't, now it is, and I'm able to see the object tf. How do I use the data to get the pose?

**Comment by matlabbe** [comment]
Look at this example: https://github.com/introlab/find-object/blob/master/src/ros/tf_example_node.cpp
