### ISSUE TITLE
consuming more ram while running 

### ISSUE THREAD

**Issue by arjunskumar** [introlab/find-object#55]
![screenshot from 2018-06-07 18-39-56](https://user-images.githubusercontent.com/13959132/41101689-761d4816-6a82-11e8-8400-2f8f7ac5d861.png)
i'm trying out for 3d object detection, i'm getting tf, pose everything correctly, but while running the program for a long time, lot of memory getting consumed and eventually causing system to slow down

**Comment by matlabbe** [comment]
Thx for reporting, the commit above should fix the memory leaks.

cheers,
Mathieu

**Comment by arjunskumar** [comment]
Hi @matlabbe Thanks, it is working fine.
