### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by shrijan00** [introlab/find-object#69]
Iḿ using a kinect v1 to detect object and get it co-ordinates. So, after installing the required package when i run ¨rosrun find_object_2d find_object_2d image:=/camera/rgb/image_raw¨
i get the following error. Anybody please help
![screenshot from 2018-10-09 17-43-39](https://user-images.githubusercontent.com/4169231/46673479-28a4d400-cbda-11e8-83ef-181d0438aa43.png)

**Comment by matlabbe** [comment]
Add a new case in this file for the encoding you are using:
https://github.com/introlab/find-object/blob/784691a0701466d7d881af64687b0fcfdcf07a02/src/ros/CameraROS.cpp#L118-L124
Use the right conversion enum in this list: https://docs.opencv.org/3.1.0/d7/d1b/group__imgproc__misc.html

**Comment by matlabbe** [comment]
**EDIT**: Update to latest version to have the commit above, you may not need to change the code afterwards.

**Comment by shrijan00** [comment]
I rectified it and its working.
