### ISSUE TITLE
Can't Publish detected objects

### ISSUE THREAD

**Issue by Kiana33** [introlab/find-object#73]
Hi,

I have successfully installed and got the find_object_2d running on my Raspberry Pi 3 with ROS Kinetic.
When I tried running 
`rosrun find_object_2d print_objects_detected`

There's nothing printed in my terminal. If I use ctrl+c to stop it shows the following message:

print_objects_detected: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Aborted

How can I get the published message in my ROS?

**Comment by matlabbe** [comment]
Is there an object detected in the UI? from this [example](http://wiki.ros.org/find_object_2d):
```
 $ roscore &
 # Launch your preferred usb camera driver
 $ rosrun uvc_camera uvc_camera_node &
 $ rosrun find_object_2d find_object_2d image:=image_raw
```

**Comment by Kiana33** [comment]
@matlabbe Thanks for your help. Yes, it detects the object in the UI. I just got it printing by simply rebooting because the Pi might not be able to take too many objects detected and it's stuck. The examples are also really helpful for my project. I really appreciate your answer.
