### ISSUE TITLE
is find_object_3d (object pose estimation) only work with stereo camera? like realsense, kinect. Can it work with Basler Tof 3D camera?

### ISSUE THREAD

**Issue by npd26** [introlab/find-object#79]

**Comment by matlabbe** [comment]
It requires a RGB/Gray image to detect objects with visual features. For 3D pose estimation, a depth registered with the color camera should be provided (like realsense, kinect). If you combine the Basler with an external RGB camera, it could work.

**Comment by npd26** [comment]
thank you.
