### ISSUE TITLE
how to use find_object_3d to find 6D pose of object using Realsense D435? 

### ISSUE THREAD

**Issue by npd26** [introlab/find-object#80]
Hello,

Can this package also work for the any object ? So, to get POSE for pick with robotic arm and RGB-D like sensor. is there any tutorial to work with Realsense canera and find_object_3d?
or will have to develop pose estimation algorithm by self?
Thanks.

**Comment by matlabbe** [comment]
This package only works with objects with visual features. To run example with realsense camera, see https://github.com/introlab/find-object/issues/91
