### ISSUE TITLE
buildtool depend on genmsg?

### ISSUE THREAD

**Issue by gavanderhoorn** [introlab/find-object#83]
Looking at the package manifest of this package I noticed that it expresses a `buildtool_depend` on `genmsg` ([here](https://github.com/introlab/find-object/blob/2cb9120f7424d2fba13932dc8755b57acb2814a7/package.xml#L13)).

The build script doesn't seem to do anything special wrt messages/services or actions, so I'm wondering whether that dependency is really needed. If it was added to be able to build messages, it should not be needed (`message_runtime` and `message_generation` are responsible pulling in the required dependencies).

**Comment by matlabbe** [comment]
It used for generating custom messages: https://github.com/introlab/find-object/blob/ef0c565b7e3b3a3e78ae5424a7536cf3dd3e9101/CMakeLists.txt#L295-L300

Indeed, based on this [tutorial](http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv):

> Open package.xml, and make sure these two lines are in it and uncommented:
> 
>   <build_depend>message_generation</build_depend>
>   <exec_depend>message_runtime</exec_depend>
> 

I did the changes in the commit above. Note that to avoid this error (tested on Kinetic):
```
$ catkin_make
Base path: /home/labm2414/catkin_ws
Source space: /home/labm2414/catkin_ws/src
Build space: /home/labm2414/catkin_ws/build
Devel space: /home/labm2414/catkin_ws/devel
Install space: /home/labm2414/catkin_ws/install
Error(s) in package '/home/labm2414/catkin_ws/src/find-object/package.xml':
Error(s):
- The manifest (with format version 1) must not contain the following tags: exec_depend

```
I replaced `exec_depend` by `run_depend` instead.

cheers,
Mathieu

**Comment by gavanderhoorn** [comment]
@matlabbe wrote:
> It used for generating custom messages [..]

5047163c already changed it, but `genmsg` is not needed for message generation. `message_generation` and `message_runtime` pull the necessary dependencies in for that.

Thanks for fixing this.
