### ISSUE TITLE
Crashes on Windows 7 laptop

### ISSUE THREAD

**Issue by agribot2** [introlab/find-object#85]
Find-object crashes about 1 in 3 times on windows 7 laptop.

 version is 0.6, opencv 3.0.0 with non-free.
Installed on a 64 bit Windows 7, on a Sony VPCF1 type laptop, running Intel i7 processor

Find-Object was installed by downloading and running the win-64 exe installer file.
 The find-object.exe file is date  10/07/2015, size 118KB

example of operation;-
start up Find-Object by clicking on the above .exe file
press space bar for default camera (laptop)
add object from file
crash

It also crashes about 1 in 5 times after ...delete object...

**Comment by matlabbe** [comment]
There is a version 0.6.2 here : https://github.com/introlab/find-object/releases
You can also try the latest version (not officially released) here: https://ci.appveyor.com/project/matlabbe/find-object/branch/master/artifacts

**Comment by agribot2** [comment]
As suggested, I've replaced version 0.6 with version 0.6.2.
The defect has not occurred after several hours.
I'll close this issue.

Many thanks for your prompt and effective help.

**Comment by agribot2** [comment]
Hi
Thanks for your very helpful and quick reply.

I'm very impressed with the find-object tool. I think many more novices and new-comers could find it interesting, if there was more tutorial type material about it available on the web.

let me explain...
I'm a new comer to computer vision, image classification and object detection, etc. I've studies opencv, and learned from various sites, such as https://www.pyimagesearch.com/2018/09/10/keras-tutorial-how-to-get-started-with-keras-deep-learning-and-python/, etc.


To understand how to use Find-Object ... I installed it and used it ! I'm impressed.
Then ...

I looked at the various sites, including ;- https://github.com/introlab/find-object/wiki ,  https://introlab.github.io/rtabmap/ ,  https://husarion.com/tutorials/ros-tutorials/4-visual-object-recognition/ , etc.

 But ... there is a lack of information about many of its functions and their operation.

For example, there does not seem to be any explanation about what the " camera from directory of images " does. Of course it becomes fairly clear by just using that function, and other simpler functions. But often novices like me will be struggling  with the question ;- is it supposed to do that ? What is it doing now ? Not all it's functions are self-explanatory to new-comers.

If there were more tutorials, I'm sure many more learners would use the tool and it's popularity would increase. Many would then be able to get into the details ( setting parameters, etc ) and your teams reputation would be greatly increased.

While I understand that basic introductory information takes time and is often tedious to the experts, well, .... we all had to start at some time !

With Regards,

Robert Agribot




________________________________

**Comment by matlabbe** [comment]
Hi Robert,

Thank you for for your support and your suggestions. There are indeed only a limited number of tutorials on Find-Object by lack of time (I am more involved on [RTAB-Map](http://introlab.github.io/rtabmap/) project right now) and it was a tool made at the beginning for people who already played a little with OpenCV's feature detection a priori. That project evolved over time to be more user friendly, even into an application that can be used directly as interface to other applications (like with TCP/IP support). I see that many new comers can learn what OpenCV's feature detection can do with Find-Object. I use it also often when I need to tune visual feature parameters for other projects. 

I am supposed to come back to Find-Object and add new features in the near future, I'll see if I can add more details to this [introductory tutorial](https://github.com/introlab/find-object/wiki/FindObjectsWithWebcam), in particular the other options we see in the menus.

Regards,
Mathieu
