### ISSUE TITLE
Can this package use infrared images instead of RGB images to detect objects?

### ISSUE THREAD

**Issue by Jiang1206** [introlab/find-object#88]
he depth camera I use can't provide color data, has a depth map and can provide infrared images, then can I use infrared data for object detection? Does anyone know? I don't know if this is feasible.

**Comment by matlabbe** [comment]
If the infrared images are gray scale images, it could work.

**Comment by Jiang1206** [comment]
Thank you！ As you said, I implemented this function using infrared images. So I closed this issue.
