### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by neoalejo** [introlab/find-object#92]
Hello, 

I am trying to install this package but I am having the following issues while running catkin_make

![image](https://user-images.githubusercontent.com/43171539/59608491-b8a9fe80-9115-11e9-943a-5761a29a33a7.png)

Any idea what it might be or how to fix it?

I am using ROS melodic and OpenCV 4.0 and I have found some compatibility issues with some scripts that I have already solved but I can't find a way to solve this one.

Thanks in advance!

**Comment by matlabbe** [comment]
Hi,

You may try to cast the `getFeature2D_ORB_scoreType()` to `ORB::ScoreType` [here](https://github.com/introlab/find-object/blob/5047163c09df5515bc505341c279045c8d9c503c/src/Settings.cpp#L813-L822):
```cpp
feature2D = new Feature2D(cv::ORB::create(
		getFeature2D_ORB_nFeatures(),
		getFeature2D_ORB_scaleFactor(),
		getFeature2D_ORB_nLevels(),
		getFeature2D_ORB_edgeThreshold(),
		getFeature2D_ORB_firstLevel(),
		getFeature2D_ORB_WTA_K(),
		(cv::ORB::ScoreType) getFeature2D_ORB_scoreType(),
		getFeature2D_ORB_patchSize(),
		getFeature2D_Fast_threshold()));
```

Note that I just updated the code to build with OpenCV4, see https://github.com/introlab/find-object/commit/413cb6820d772c93595b06b2d02c8d11dc2cf330

cheers,
Mathieu

**Comment by neoalejo** [comment]
Thanks, this solved the issue :)
