### ISSUE TITLE
Compiling error with OpenCV 3.4.6 contrib and CUDA activated

### ISSUE THREAD

**Issue by FPSychotic** [introlab/find-object#94]
Hi I´m receiving this error:

``[ 52%] Building CXX object src/CMakeFiles/find_object.dir/Settings.cpp.o
In file included from /usr/local/include/opencv2/core.hpp:56:0,
                 from /usr/local/include/opencv2/highgui.hpp:46,
                 from /usr/local/include/opencv2/highgui/highgui.hpp:48,
                 from /home/i-jefry/ros_catkin_ws/src/findobject/src/../include/find_object/Camera.h:33,
                 from /home/i-jefry/ros_catkin_ws/src/findobject/src/Settings.cpp:28:
/usr/local/include/opencv2/core/traits.hpp: In instantiation of ‘struct cv::traits::Type<cv::KeyPoint>’:
/usr/local/include/opencv2/core/mat.inl.hpp:95:32:   required from ‘cv::_InputArray::_InputArray(const std::vector<_Tp>&) [with _Tp = cv::KeyPoint]’
/home/i-jefry/ros_catkin_ws/src/findobject/src/Settings.cpp:424:43:   required from here
/usr/local/include/opencv2/core/traits.hpp:366:8: error: ‘type’ is not a member of ‘cv::DataType<cv::KeyPoint>’
 { enum { value = DataType<T>::type }; };
        ^
src/CMakeFiles/find_object.dir/build.make:334: recipe for target 'src/CMakeFiles/find_object.dir/Settings.cpp.o' failed
make[2]: *** [src/CMakeFiles/find_object.dir/Settings.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2080: recipe for target 'src/CMakeFiles/find_object.dir/all' failed
make[1]: *** [src/CMakeFiles/find_object.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I couldnt find nobody with the same error here, but I did with with perception, and they fixed with some line #include .... and making traits deprecated, if I find the post I will write here.
Im begginner and is impossible for me fix this without help.  thank you

**Comment by FPSychotic** [comment]
Only tell that the standalone version compiled properly, I used runtime CUDA flag. I tried with theros version but send the same error

**Comment by FPSychotic** [comment]
I found how to fix  the issue in the lines CVCUDA::GpuMat keypointsGpu(keypoints);

but it result that is fixed in Master, but I instaled melodic as Im new and I do not understand the difference of master and the one of your ros distro. thanks

**Comment by matlabbe** [comment]
Hi,

The master branch is the most up-to-date code. The melodic-devel or kinetic-devel branches should match the released binary version in the corresponding ros distro.

cheers,
Mathieu
