### ISSUE TITLE
tf decays when playing rosbag file for kinect v2.0

### ISSUE THREAD

**Issue by cardboardcode** [introlab/find-object#96]
Hi introlab, thank you for maintaining this extremely useful ROS package for all. 

This issue is in regards to playing a rosbag file simulating the inputs from an **XBOX Kinect ONE v2.0** sensor. 

### Issue Description
```
```
When playing the aforementioned **rosbag** file and running the `find_object_3d_kinect2` functionality, I observed that the __broadcasted tf frames__ will decay after a period of time (even though the object is still being detected and tf is still being published supposedly.)  

`rosbag play -l /path/to//your/rosbag.bag`
`roslaunch find_object_2d find_object_3d_kinect2.launch`

As opposed to running `find_object_3d_kinect2` with a real Kinect, the __broadcasted tf frames__ does not decay over time.

`roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true`
`roslaunch find_object_2d find_object_3d_kinect2.launch`

```
```

### Temporary Workaround
```
```
After a few days of googling, I deduced the issue to be related to using an [outdated rosbag file ](https://wiki.ros.org/tf) (See under `tf_old`). See below for the abstract.
```
Subscribed Topics
/tf_old (tf/tfMessage)

    Old transform tree. This is usually published by remapping playback of a bag file. 
You may need to set use_sim_time true for the bag file transforms to be accepted. 
```

In the end, to stop the __broadcasted tf frames__ from decaying when using the **rosbag** file, I included the following lines and arguments as follows in the [`find_object_3d_kinect2.launch`](https://github.com/introlab/find-object/blob/master/launch/find_object_3d_kinect2.launch) file:
```xml
<launch>
        <param name="/use_sim_time" value="true"/>
...
...
         <node pkg="rosbag" type="play" name="rosbag" args="--clock -l /path/to//your/rosbag.bag">
</launch>
```
```
```
### Enquiry
Is it possible to have a feature developed for the ROS package allowing it to run smoothly with rosbag files?

Apologies if this is a trivial request.

**Comment by matlabbe** [comment]
Hi,

This is a ROS issue (or feature?). The approach you have shown is the standard way to play a rosbag which contains TF, so that the frames are correctly stamped with the simulated clock.  

In general:
```bash
$ roslaunch find_object_3d_kinect2.launch
$ rosparam set use_sim_time true
$ rosbag play --clock mybag.bag
```

For convenience, you can add `use_sim_time` in launch file [find_object_3d_kinect2.launch](https://github.com/introlab/find-object/blob/master/launch/find_object_3d_kinect2.launch):
```xml
<launch>
<arg name="use_sim_time" default="false"/>
<param name="use_sim_time" value="$(arg use_sim_time)"/>
...
</launch>
```
so you can start the launch file in simulation/rosbag with:
```bash
$ roslaunch find_object_3d_kinect2.launch use_sim_time:=true
$ rosbag play --clock mybag.bag
```

See also https://answers.ros.org/question/9106/rosbag-play-tf-static_transform_publisher/?answer=13127#post-id-13127

> To deal with the timing issue you should set use_sim_time parameter and playback the bag file with the clock option enabled. 

cheers,
Mathieu

**Comment by cardboardcode** [comment]
Thanks, Mathieu @matlabbe 

Noted. Will adopt your approach since it is more proper. 

Will close this issue then.
